# Generated by Django 2.0.1 on 2018-01-10 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0004_categoria_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='status',
            field=models.CharField(blank=True, choices=[('C', 'Concluído'), ('CD', 'Cancelada')], default='', max_length=5, verbose_name='Status'),
        ),
    ]
